package com.example.joshuaevanarijanto.dicodingrecyclerview;

import java.util.ArrayList;

/**
 * Created by Joshua Evan Arijanto on 7/29/2019.
 */

public class DreamData {

    public static String[][] data = new String[][]{

            {"Bill Gates",
                    "Patience is a key element of success",
                    "Bill is a visionary person and works very hard to achieve his vision. his belief in high intelligence and hard work has put him where he is today. The Success Story of Bill Gates. His drive and resilience has landed him so many grand achievements." +
                            "\n\n" +
                            "Today bill gates is known as a prominent American entrepreneur, investor, philanthropist with a terrific career in a development of software for personal-computers. The co-founder of Microsoft Corporation, one of the most recognized brands in the computer industry; nearly every computer has at least one Microsoft product installed. Due to the hard work, he has achieved not only the prosperity of the company, but also the title of one of the richest people on Earth. " +
                            "\n\n" +
                            "Gates has been No. 1 for many years on the Bloomberg Billionaires List, but Carlos Slim Helu took No. 1 spot in 2010. And in May 2013, with a fortune of $72 billion Bill Gates became the richest man on the planet again and retook the world’s richest title from Carlos Slim. Bill Gates’ net worth was $79.3 billion as of April 09, 2015. Gates would have a significantly higher net worth if he didn’t give so much money away.",
                    "https://amp.businessinsider.com/images/5b8981c68ea82f33008b5aa4-750-563.jpg"

            },
            {"Mark Zuckerberg",
                    "The biggest risk is not taking any risk",
                    "While many intelligent people attend Harvard University, Mark Zuckerberg became known quickly as the go-to computer programmer on campus. By his sophomore year, he had already built two programs: CourseMatch and FaceMash. Both programs became wildly popular, but the university shut down the latter program after it was deemed to be inappropriate. Based on his acclaim on campus, Zuckerberg partnered with friends to create a social networking site that allowed Harvard students to connect with each other. The site officially went live in June 2004 under the name \"The Facebook,\" and Zuckerberg ran it out of his dorm room. After his sophomore year, Zuckerberg dropped out of college to pursue what was then called Facebook full-time. The website reached 1 million users by the end of 2004. This explosion of user growth attracted the attention of many venture capital (VC) firms, and Zuckerberg eventually moved out to Silicon Valley in 2005. " +
                            "\n" +
                            "Facebook received its first round of venture capital investments from VC firm Accel Partners, which invested $12.7 million in the site that was still only open to Ivy League students. By the end of 2005, however, Facebook had opened up to students attending other schools, causing the website to reach 5.5 million users. Since 2005, Facebook has received numerous acquisition offers from the likes of Yahoo and Microsoft, has been through legal battles, and has greatly increased the its users. On July 25, 2018, Facebook released Q2 earnings. " +
                            "\n" +
                            "The company reported that daily active users averaged 1.47 billion for June 2018, an increase of 11% year-over-year. Monthly active users totaled 2.23 billion as of June 30, 2018, an increase of 11% year-over-year. As of July 30, 2018, the company has a market cap of $483 billion. Zuckerberg owns 14.18 million Class A Facebook shares in a series of funds, as of July 25, 2018. He also owns  441.6 million Class B shares. With control of over nearly 89% of Class B shares, Zuckerberg holds 60% of voting rights in the company.",
                    "https://media.bizj.us/view/img/10304965/3049457381-8*750xx4000-2255-0-61.jpg"
            },
            {"Linus Torvalds",
                    "Talk is cheap. Show me the code.",
                    "After graduating with a master’s in Computer Science from NODES research group, Linus also briefly joined the Finnish Army in the summer of 1989, taking the rank of second lieutenant ballistic calculation officer later on.linux kernel architect linus torvaldsLinus served as the principle force behind the development of the Linus Kernel in 1991, but the inspiration for this invention came from his exposure to the MINX which is a stripped down version the UNIX operating system from Andrew Tanenbaum’s book “Operating Systems: Design and Implementation”.Inspired by the clear structure and the underlying philosophy of the UNIX operating system, Linus went on work on the prototype for the Linux operating system for implementing the same toIntel 80386based IBM personal computer even before he received his MINX copy." +
                            "\n\n" +
                            "linus torvalds with linux kernel developersTorvalds earned most of his $150 Million through Linux Kernel, apart from earning an annual salary of $10 million with the position he held at Transmeta, Open Source Development Labs and Free Standard Group. Free Standard Group was then merged and became the Linux Foundation, where he became the chief architect of the Linux Kernel and is now the project’s coordinator.Over two percent of the Linux Kernel was written by Torvalds himself, the maximum a single person has contributed to a open operating system kernel till day. Hence, he holds the highest authority to decide the new codes that are incorporated into the standard Linux Kernel." +
                            "\n\n" +
                            " He also owns the “Linux” trademark and monitors the use of it through the “ Linux  Mark Institute”.linus torvalds with jim zemlinLinus has not stopped his innovation at that. He wenton to create the Revision Control System,Git and also the diving log software called “Subsurface”.His contribution to the information technology has earned many accolades such as “IEEE Computer Pioneer Award”, “Internet Hall Of Fame”, “Millennium Technology Prize”, “Vollum Award” from Reed college etc. Torvalds is the 17th Most Important Person of the Century in the “Time 100”. He also has an asteroid named in his honor called “9793 tor”",
                    "https://tecnoblog.net/wp-content/uploads/2018/01/LinuxCon-Europe-Linus-Torvalds-700x394.jpg"
            },
            {"Gennady Korotkevich",
                    "a.k.a Tourist",
                    "Korotkevich was born in Gomel (Homiel), southeastern Belarus. His parents, Vladimir and Lyudmila Korotkevich, are programmers in the mathematics department at Francysk Skaryna Homiel State University. At age 6, he became interested in his parents' work. When he was 8, his father designed a children's game he could use to learn programming. His mother consulted departmental colleague Mikhail Dolinsky, who gave the boy a small book to read. Dolinsky, one of the top computer science teachers in Belarus, recalled, \"A month went by, and then another one ... No news from Gena. Then suddenly Lyudmila comes by and brings me a programming notebook: when summer and football were over, her son sat at the computer. As a second grader at a national competition, he took second place, which gained him automatic entry in a technical university without taking any entrance exams. Somehow he solved the problem of a body immersed in water. At that time, Gena didn't even know about Archimedes' principle of buoyancy. Korotkevich first grabbed global attention when he qualified for the 2006 International Olympiad in Informatics (IOI) at the age of 11, which itself is a world record by a large margin. He took the silver medal at his first IOI event, and received gold medals 2007 to 2012. To date he is the most successful competitor in IOI's history. At the 2009 IOI in Plovdiv, the then 14-year-old Korotkevich said of his success, \"I try various [strategies], and one of them is the right one. I am no genius. I am simply good at it.\" He said he spent no more than three to four hours each day at the computer, and his preferred hobbies are football and table tennis. In the fall of 2012, he moved to Russia to attend ITMO University. " +
                            "\n\n" +
                            "In the summer of 2013, he helped ITMO defeat Shanghai Jiao Tong University and the University of Tokyo to win the 37th International Collegiate Programming Contest World Finals, held in Saint Petersburg. He also won the Google Code Jam in 2014, 2015, 2016, 2017 and 2018. In a 2014 interview, Korotkevich said he was unsure of his career plans after graduation. \"What happens next is yet to be decided,\" he said. \"I don't have any concrete or long-term plans. I've only finished my sophomore year at university. For me it's important to get an education first and then decide about working. Maybe I'll go into science. But again, I really have not decided yet.\" In a 2017 interview, Korotkevich said \"I've gotten job offers from Google and Yandex several times, but didn't take them... I am getting a Masters in Computer Science at ITMO, afterward I think that's what I'll do.\" ",
                    "https://cdn-04.independent.ie/incoming/article31571875.ece/ef2d2/AUTOCROP/w620/Gennady%20Korotkevich.jpg"
            },
            {"Elon Musk",
                    "When something is important enough, you do it even if the odds are not in your favor.",
                    "Immediately after leaving Stanford, Musk teamed up with his brother Kimbal and created an IT company called Zip2. Musk describes the first two years as a grind, but eventually local and national newspapers began to use Zip2 to offer additional services to customers. " +
                            "\n\n" +
                            "In 1999, search engine AltaVista bought Zip2 for $307 million, a record deal at the time. By March 2000, Musk was working with Peter Thiel and Max Levchin on X.com, which later became PayPal. Musk was named chairman and CEO of PayPal in 2001. One year later, eBay bought PayPal for $1.5 billion (Musk's share was roughly $180 million). Musk believed he finally had enough capital to focus on his real passion: space engineering. PayPal would be Musk's last great venture into Internet businesses. Musk joined forces with engineers Martin Eberhard and Marc Tarpenning at Tesla Motors in 2004. He participated in the design of the first electric car, the Tesla Roadster. Tesla has since become one of the most popular and coveted car brands in the world, even beating out GM and Ford to become the highest ranked American auto brand as ranked by Consumer Reports in 2018. Musk has also taken his ambitions to the final frontier with SpaceX, which has landed several high profile contracts collaborating with NASA and the Air Force to design rockets and conduct military missions. Musk hopes to collaborate in the mission to send an astronaut to Mars by 2025. The majority of Musk's $20.8 billion net worth is tied up in Tesla. " +
                            "\n\n" +
                            "As of June 28, 2018, he owns 33,737,921 shares in Tesla which is valued at roughly $11.6 billion. Tesla released a new compensation structure for Musk in January 2018. This new structure gives him no salary, but instead he will make money by achieving higher and higher market cap milestones over the next ten years. The deal should help Tesla ensure Musk sticks around for a long time. Musk is considered a hero by many in the technology and engineering fields for his brilliant work and outspoken aspirations for space travel. He is also a noted celebrity in the alternative energy crowd, thanks to his work on electric cars.",
                    "https://amp.businessinsider.com/images/59f8dc483e9d25db458b5dfc-750-563.jpg"
            },
            {
                    "Jeff Bezos",
                    "Work Hard, Have Fun, Make History",
                    "Bezos quit D.E. Shaw in 1994 and moved to Seattle to tap into the potentials of the internet market by opening an online bookstore. He made the decision by drawing up a list of possible products that he could sell via the Internet, including CDs, software, and hardware. In the end, books were the obvious choice because of the wide range of titles in existence. Another advantage of an internet store was a then-recent U.S. Supreme Court ruling that mail-order catalogs did not have to pay taxes in states where they did not have a physical presence. In other words – Bezos paid zero tax for the products he sold via the internet."+"\n" +
                            "Bezos decided that Seattle would be a perfect place for his new business at the time because of the tremendous pool of hi-tech talent. While his wife MacKenzie drove them from Texas, he spent the time laying out a business plan on his laptop and calling up possible investors. Jeff Bezos managed to raise $1 million from his family and friends, enough to set up his business in the garage of his Seattle home.\n" +
                            "\n" +
                            "Bezos initially incorporated the company as “Cadabra” on July 5, 1994. However, a year later he considered to change it when his lawyer misheard the word as “cadaver,” but that was not the worst one. Another alternative was “MakeItSo.com” – a catchphrase from Captain Picard in Jeff’s beloved Star Trek. It could have also been “aard.com,” which would help push the company to the front of website listings. Jeff and MacKenzie also registered the domain names Awake.com, Browse.com, Bookmall.com, and Relentless.com (the latter one still redirects to Amazon.com). Eventually, Bezos decided on Amazon.com after looking through the words that start with A in the dictionary. Bezos liked the resonance between one of the planet’s longest rivers and largest bookstore.\n" +
                            "\n" +
                            "Jeff and MacKenzie set everything up in their two-bedroom house, with extension cords running down to the garage, and three Sun micro stations on tables that Jeff made from $60 doors. Ironically, staff meetings would take place at the local Barnes & Noble bookstore. When everything was ready, Jeff and MacKenzie hurled up 300 people to try the test site when it was up and running, and the code worked seamlessly on different computer platforms. After opening the website on July 16, 1995, they told their 300 beta users to spread the word around and set up a bell to ring every time Amazon made a sale. The Bell did not stay there for long as Amazon abruptly exploded selling books in all 50 states and 45 foreign countries within a month. By September 1995, the sales had summed up to $20,000 a week.\n" +
                            "\n" +
                            "Bezos was determined on taking the company public with an IPO, and began recruiting large amounts of people. These included a few DESCO employees, executives from competing company Barnes & Noble, software company Symantec, and two people from Microsoft – vice president of engineering Joel Spiegel, and David Risher, who would later become head of retail. With a team of extraordinary people in his senior leadership ranks (who would formally become known as the J-Team) Bezos was convinced that “If we get this right, we might be a $1 billion company by 2000.”\n" +
                            "\n" +
                            "Going public would not only solidify customer trust but would also outcompete other bookstores who would soon begin setting up websites of their own, Bezos thought. Barnes & Noble were the biggest competition. They possess the legacy of establishing ‘the book superstore,’ taking little independent bookstores out of business between 1991 and 1997, and revolutionizing bookselling. In 1996, their sales estimated to $2 billion while Amazon was lagging behind with $16 million that same year.\n" +
                            "\n" +
                            "The Riggio brothers – Leonard Riggio and Steve Riggio – who owned Barnes & Noble, came to Seattle to have dinner to discuss a business deal with Bezos and Tom Alberg, founder and managing partner of the venture capital firm Madrona Venture Group, and a director of Amazon.com. Knowing Leonard Riggio’s character – a tough-as-nails businessman from the Bronx dressed in an expensive suit with a taste for fine art – the pair decided on a strategy of caution and flattery. The Riggios came on hard and threatening and announced that they were planning to open their own website – one that would take Amazon out of the competition. They offered various collaborations, including setting up a website together, and licensing Amazon’s technology. Bezos and Alberg said they would think about it at dinner, but after a phone conversation decided that this collaboration would not work.\n" +
                            "\n" +
                            "While the Riggios were home setting up their website, Jeff Bezos and Amazon’s first CFO, Joy Covey (April 25, 1963 – September 18, 2013), traveled around the United States and Europe to pitch Amazon to potential investors. They had a solid background, with millions of sales within three years of existing, and an easily accessible single warehouse and inventory; in contrast with other retailers who had their products spread throughout stores around the country. They also used a ‘negative operating cycle’ which meant that customers would pay with their credit cards when the product shipped, but Amazon would settle its accounts with distributors every few months. Almost every investor asked the two whether they were going to expand to other categories, and, at the time, Bezos responded that they settled on books. He wanted to get some investments from an IPO, but he did not want his rivals to follow in his footsteps, hence withholding lots of valuable data from investors. Everyone firmly believed that once Barnes & Noble comes in, Amazon is Amazon.Toast.\n" +
                            "\n" +
                            "On May 12, 1997, three days before the IPO, Barnes & Noble filed the lawsuit against Amazon in federal court for falsely claiming to be “Earth’s Largest Bookstore.” It happened during the seven-week SEC-mandated “quiet period” meaning that Bezos could not talk to the press before the IPO. Ironically, the lawsuit only gave Amazon more attention. The two companies competed fiercely for around a year after Amazon finally went public. Barnes & Noble boasted a broader catalog while Amazon tried to track down books from independent dealers and antique shops. Barnes & Noble got a $200 million investment from German media giant Bertelsmann and also took the company public. Bezos then swiftly expanded Amazon’s product line, and changed “Earth’s Biggest Bookstore” to “Books, Music and More” – leaving Barnes & Noble, as one writer put it, “wrapping its arms around the neck of a phantom.”\n" +
                            "\n" +
                            "The stock traded below its IPO price at first and Bezos worried that the company might lose a significant portion of its investment. On May 15, 1997, the stock price was set for a $12-to-$14 range on NASDAQ (AMZN) on the IPO day. Then it increased from $14 to $16 before the Amazon’s investment bankers settled on the $18 price. Amazon.com raised $54 million in its IPO and the online bookstore market value reached $438 million. Amazon put 3 million shares on the block. It was a blockbuster year for Amazon as they experienced a 900 percent growth in annual revenue. Bezos’s family had each invested $10 thousand dollars from the start as a backup plan – it was a major part of their life savings. As six percent of owners of Amazon, they officially became multimillionaires by the end of the decade, and Jeff was named Time’s Person of the Year in 1999.\n" +
                            "\n",
                    "https://awsimages.detik.net.id/community/media/visual/2018/09/21/67ff935a-a5cf-42f0-b911-d24dcb7b8d3d.jpeg?w=700&q=90"

            },
            {
                    "Larry Page and Sergey Brin",
                    "If you’re not doing some things that are crazy, then you’re doing the wrong things.",
                    "In the fall of 1997, Larry and Sergey brainstormed a catchier name of BackRub. They turned to their mate Sean Anderson for help. Anderson suggested the name Googolplex, a huge number, the digit 1 followed by 10 to a 100 degrees. Sergey and Larry liked the name and proposed to shorten it to Googol. The word googol indicates the digit 1 followed by 100 zeros.\n" +
                            "\n" +


                            "\n" +
                            "Anderson commented: “I typed in G-o-o-g-l-e and misspelled it on my workstation, and that was available. Larry found that acceptable, and he registered it later that evening and wrote it on the whiteboard: Google.com”.\n" +
                            "\n" +
                            "Soon, one of their office colleagues noticed that they had misspelled googol number and pointed out on it. However, the Google.com had been already registered.\n" +
                            "\n" +
                            "Initially, it has been hosted on the root domain of Stanford University at google.stanford.edu. The domain name google.com was registered on September 15, 1997.\n" +
                            "\n" +
                            "During the first half of 1998, the Sergey and Larry were involved in the development of a new and promising search engine technology. Larry Page’s dorm room at Stanford University served as the data center while the Sergey Brin’s dorm room – the business office. Initially, Brin and Page did not want to create Google as business and considered the search engine as the basis for a scholarly research project to obtain their Ph.D. degrees.\n" +
                            "\n" +

                            "\n" +
                            "They noticed that Google became too popular among Stanford students, and they started thinking how to expand Google beyond the Stanford walls. First, they attempted to sell their idea to AltaVista for $1 million but Paul Flaherty, the inventor of AltaVista, rejected their proposal. Sergey and Larry also tried to sell it to Yahoo!, Excite, but things turned out a different way.\n" +
                            "\n" +
                            "After several unlucky attempts of selling it, they created a business plan and started looking for angel investors who would provide funds for an exchange of ownership portion of their company. David Cheriton, their computer science professor, introduced them Andy Bechtolsheim, who was a Vice President of Cisco Systems (later co-founder of Sun Microsystems). He was very interested in the idea and wrote out a check for $100,000.\n" +
                            "\n" +
                            "Humble Beginnings in a Garage\n" +
                            "In the middle of 1998, Brin and Page paused their studies at Stanford University. Their parents were not pleased with this decision.\n" +
                            "\n" +
                            "On September 7, 1998, Google was incorporated as a limited liability company, Google Inc. Larry Page became CEO, and Sergey Brin became President. Their first office was a rented garage from Susan Wojcicki, a sister of Sergey Brin’s girlfriend Anne Wojcicki, which was located in Menlo Park, California. Despite, Google processed around 10,000 requests per day PC Magazine featured it on the list of Top 100 best Websites and Search Engines of 1998. Soon Craig Silverstein joined their team as the first Google’s employee. In the following year, the company moved into the new office in Palo Alto.\n" +
                            "\n" +


                            "The number of satisfied users has been growing rapidly, and the word “Google” was popping from all over the place. The company needed investments for the business expansion, but at the same time, Brin and Page did not want to lose control. The partners wanted Google to adhere its mission – “to organize the world’s information and make it universally accessible and useful.” That was a starting point where they proved that they were able to find original solutions not only in the area of new technologies but also in running the business.\n" +
                            "\n" +
                            "Venture Investments\n" +
                            "In June 1999, Brin and Page managed to convince two competing venture capital firms – Sequoia Capital and Kleiner Perkins Caufield & Byers – to fund Google and attracted investments of $25 million. According to David A. Vise, the co-author of The Google Story book, it was a classic maneuver “divide and conquer.” It allowed Brin and Page to prevent the possibility of a significant influence from any of the investors, despite the fact that the representatives of the two venture capital firms have entered the board of directors.\n" +
                            "\n" +
                            "Being at Stanford Sergey and Larry co-authored a research paper The Anatomy of a Large-Scale Hypertextual Web Search Engine, which contained a prototype of a large-scale search engine, called Google. In this research paper, they wrote: “We expect that advertising funded search engines will be inherently biased towards the advertisers and away from the needs of the consumers.”\n" +
                            "\n" +
                            "Sergey and Larry were against banner advertising – they were proud of their clean and simple design. Their main purpose was to search, not to sell. While at the same time, other search engines were trying to sell banner adverts on their websites.\n" +
                            "\n" +
                            "By the end of 1999, Google processed approximately 7 million searches per day, and in the middle of 2000, it handled an average of 18 million searches per day. The company spent $500,000 a month in operating costs with the continuous increase. They had to figure something out and re-consider their non-advertising policy to keep the company afloat.\n" +
                            "\n" +
                            "First Profit\n" +
                            "To become a profitable company Sergey and Larry decided to display sponsored advertisements, but not on the homepage. Instead, they agreed to show highlighted links separated from organic search results. In the US, advertisers spent billions of dollars on outdoor advertising; however, sometimes it was not quite effective. Brin and Page offered a solution to display sponsored adverts based on the searches of users. If users searched on Google for more information about cars, they could click on a sponsored link to learn more. Thus, on October 23, 2000, the partners released Google AdWords, an online advertising service.\n" +
                            "\n" +
                            "It is interesting to know that Paul Buchheit, a Google engineer, invented the original Google’s motto “Don’t Be Evil” in July 2001. During a Google’s employee meeting, where they wanted to discuss main principles, he came up with it. It stuck in the head and became the original motto of the corporation.\n" +
                            "\n" +

                            "\n" +
                            "The ability to think creative demonstrated itself during the Dot-com bubble. The rival companies, such as AltaVista, Excite, and Lycos have been spending millions on advertising and marketing campaigns to create brands. While at the same time, Google executives remained calm and worked hard to improve its search engine to meet the users’ expectations. Sergey Brin believed that in terms of marketing, Google might rely on the users, as a significant part of those who used the services of the search engine would recommend it to others. In December 1999, when their second employee, Marissa Mayer, changed the search results font for a better user experience, she received a significant protest from Google’s users. Sergey and Larry always preferred their home and search result pages remain unchanged.\n" +
                            "\n" +
                            "In May 2000, the Google team received a Webby Award and People’s Choice Award for the technical achievement. The following month, Google officially became the world’s largest search engine with the announcement of reaching 1 billion URL in its index.",
                    "https://www.ft.com/__origami/service/image/v2/images/raw/http%3A%2F%2Fcom.ft.imagepublish.prod.s3.amazonaws.com%2F72c3c636-ba55-11e3-aeb0-00144feabdc0?fit=scale-down&source=next&width=700"
            },
            {
                "Andrew Ng",
                    "AI is the new electricity",
                    "Andrew Yan-Tak Ng (Chinese: 吳恩達; born 1976) is a Chinese-American computer scientist, global leader in AI, inventor, business executive, investor and entrepreneur of the Silicon Valley who has made major contributions to artificial intelligence, deep learning, robotics, and machine learning. Ng co-founded and led Google Brain and was a former Vice President and Chief Scientist at Baidu, building the company's Artificial Intelligence Group into a team of several thousand people. He is an adjunct professor at Stanford University (formerly associate professor and Director of its AI Lab).\n" +
                            "\n" +
                            "Ng is also a pioneer in online education and co-founded Coursera and deeplearning.ai. With his online courses, he has successfully spearheaded many efforts to \"democratize deep learning.\" Since 2018 he launched and currently heads AI Fund, initially a $175-million investment fund for backing artificial intelligence startups. He has founded Landing AI, which provides AI-powered SaaS products and Transformation Program to empower enterprises into cutting-edge AI companies.\n" +
                            "\n" +
                            "He is one of the most prolific researchers in the field and has been described as one of the most important people in AI, with his work helping incite the recent revolution in deep learning."+"\n"+
                            "Founding of Coursera\n" +
                            "Key ideas drew from a variety of people. Within Stanford, they include Daphne Koller with her \"blended learning experiences\" and co-designing a peer-grading system, John Mitchell (Courseware, a Learning Management System), Dan Boneh (using machine learning to sync videos, later teaching cryptography on Coursera), Bernd Girod (ClassX), and others. Outside Stanford both Ng and Thrun credit Sal Khan of Khan Academy as a huge source of inspiration. Ng was also inspired by lynda.com and the design of the forums of Stack Overflow.\n" +
                            "\n" +
                            "Ng started the Stanford Engineering Everywhere (SEE) program, which in 2008 published a number of Stanford courses online for free. Ng taught one of these courses, \"Machine Learning\", which includes his video lectures, along with the student materials used in the Stanford CS229 class. It offered a similar experience to MIT's Open Courseware except it aimed at providing a more \"complete course\" experience, equipped with lectures, course materials, problems and solutions, etc. The SEE videos were viewed by the millions and inspired Ng develop and iterate new versions of online tech.\n" +
                            "\n" +
                            "Widom, Ng, and others were ardent advocates of Khan-styled tablet recordings, and between 2009–2011, several hundred hours of lecture videos recorded by Stanford instructors were recorded and uploaded. Ng tested some of the original designs with a local high school to figure the best practices for recording lessons.\n" +
                            "\n" +
                            "In October 2011, the \"applied\" version of the Stanford class (CS229a) was hosted on ml-class.org and launched, with over 100,000 students registered for its first edition. The course featured quizzes and graded programming assignments and became one of the first and most successful Massive open online courses (MOOCs) created by a Stanford professor.\n" +
                            "\n" +
                            "Two other courses on databases (db-class.org) and AI (ai-class.org) were launched. The ml-class and db-class ran on a platform developed by students, including Frank Chen, Jiquan Ngiam, Chuan-Yu Foo, and Yifan Mai. Word spread through social media and popular press. The three courses were 10 weeks long, and over 40,000 \"Statements of Accomplishment\" were awarded.\n" +
                            "\n" +
                            "Ng tells the following story on the early days of Coursera:\n" +
                            "\n" +
                            "In 2011, I was working with four Stanford students. We were under tremendous pressure to build new features for the 100,000+ students that were already signed up. One of the students (Frank Chen) claims another one (Jiquan Ngiam) frequently stranded him in the Stanford building and refused to give him a ride back to his dorm until very late at night, so that he no choice but to stick around and keep working. I neither confirm nor deny this story.\n" +
                            "\n" +
                            "His work subsequently led to his founding of Coursera with Koller in 2012. As of 2019, the two most popular courses on the platform were taught and designed by Ng: \"Machine Learning\" (#1) and \"Neural Networks and Deep Learning\" (#2)."
                    ,
                    "https://syncedreview.com/wp-content/uploads/2017/12/Andrew-Ng_preview.jpeg"

            },
            {
                "Dijkstra",
                    "Simplicity is prerequisites for reliability",
                    "Edsger Wybe Dijkstra 11 May 1930 – 6 August 2002) was a Dutch systems scientist, programmer, software engineer, science essayist, and pioneer in computing science A theoretical physicist by training, he worked as a programmer at the Mathematisch Centrum (Amsterdam) from 1952 to 1962. A university professor for much of his life, Dijkstra held the Schlumberger Centennial Chair in Computer Sciences at the University of Texas at Austin from 1984 until his retirement in 1999. He was a professor of mathematics at the Eindhoven University of Technology (1962–1984) and a research fellow at the Burroughs Corporation (1973–1984).\n" +
                            "\n" +
                            "One of the most influential figures of computing science's founding generation, Dijkstra helped shape the new discipline from both an engineering and a theoretical perspective. His fundamental contributions cover diverse areas of computing science, including compiler construction, operating systems, distributed systems, sequential and concurrent programming, programming paradigm and methodology, programming language research, program design, program development, program verification, software engineering principles, graph algorithms, and philosophical foundations of computer programming and computer science. Many of his papers are the source of new research areas. Several concepts and problems that are now standard in computer science were first identified by Dijkstra or bear names coined by him. As a foremost opponent of the mechanizing view of computing science, he refuted the use of the concepts of 'computer science' and 'software engineering' as umbrella terms for academic disciplines.\n" +
                            "\n" +
                            "Until the mid-1960s computer programming was considered more an art (or a craft) than a scientific discipline. In Harlan Mills's words (1986), \"programming [before the 1970s] was regarded as a private, puzzle-solving activity of writing computer instructions to work as a program\". In the late 1960s, computer programming was in a state of crisis. Dijkstra was one of a small group of academics and industrial programmers who advocated a new programming style to improve the quality of programs. Dijkstra, who had a background in mathematics and physics, was one of the driving forces behind the acceptance of computer programming as a scientific discipline. He coined the phrase \"structured programming\" and during the 1970s this became the new programming orthodoxy. His ideas about structured programming helped lay the foundations for the birth and development of the professional discipline of software engineering, enabling programmers to organize and manage increasingly complex software projects.As Bertrand Meyer (2009) noted, \"The revolution in views of programming started by Dijkstra's iconoclasm led to a movement known as structured programming, which advocated a systematic, rational approach to program construction. Structured programming is the basis for all that has been done since in programming methodology, including object-oriented programming.\"\n" +
                            "\n" +
                            "The academic study of concurrent computing started in the 1960s, with Dijkstra (1965) credited with being the first paper in this field, identifying and solving the mutual exclusion problem. He was also one of the early pioneers of the research on principles of distributed computing. His foundational work on concurrency, semaphores, mutual exclusion, deadlock (deadly embrace), finding shortest paths in graphs, fault-tolerance, self-stabilization, among many other contributions comprises many of the pillars upon which the field of distributed computing is built. Shortly before his death in 2002, he received the ACM PODC Influential-Paper Award in distributed computing for his work on self-stabilization of program computation. This annual award was renamed the Dijkstra Prize (Edsger W. Dijkstra Prize in Distributed Computing) the following year, in his honor. As the prize, sponsored jointly by the ACM Symposium on Principles of Distributed Computing (PODC) and the EATCS International Symposium on Distributed Computing (DISC), recognizes that \"No other individual has had a larger influence on research in principles of distributed computing\"" ,
                    "https://i2.wp.com/ciblogassets.s3.amazonaws.com/crowdblog/asset/242/Dijkstra.png?ssl=1"
            },
            {
                "James Gosling",
                    "People think of security as a noun, something you go buy. In reality, it's an abstract concept like happiness. Openness is unbelievably helpful to security.",
                    "James Gosling received a Bachelor of Science from the University of Calgary and his M.A. and Ph.D. from Carnegie Mellon University, all in computer science. He wrote a version of Emacs called Gosling Emacs (Gosmacs) while working toward his doctorate. He built a multi-processor version of Unix for a 16-way computer system while at Carnegie Mellon University, before joining Sun Microsystems. He also developed several compilers and mail systems there.\n" +
                            "\n" +
                            "Gosling was with Sun Microsystems between 1984 and 2010 (26 years). He is known as the father of the Java programming language. He got the idea for the Java VM while writing a program to port software from a PERQ by translating Perq Q-Code to VAX assembler and emulating the hardware. He left Sun Microsystems on April 2, 2010 after it was acquired by the Oracle Corporation, citing reductions in pay, status, and decision-making ability, along with change of role and ethical challenges. He has since taken a very critical stance towards Oracle in interviews, noting that \"during the integration meetings between Sun and Oracle, where we were being grilled about the patent situation between Sun and Google, we could see the Oracle lawyer's eyes sparkle.\" He clarified his position during the Oracle v Google trial over Android: \"While I have differences with Oracle, in this case, they are on the right. Google totally slimed Sun. We were all really disturbed, even Jonathan Schwartz; he just decided to put on a happy face and tried to turn lemons into lemonade, which annoyed a lot of folks on Sun.\" However, he approved of the court's ruling that APIs should not be copyrightable.\n" +
                            "\n" +
                            "In March 2011, Gosling left Oracle to work at Google. Six months later, he followed his colleague Bill Vass and joined a startup called Liquid Robotics. In late 2016, Liquid Robotics was acquired by Boeing. Following the acquisition, Gosling left Liquid Robotics to work at Amazon Web Services as Distinguished Engineer in May 2017.\n" +
                            "\n" +
                            "He is an advisor at the Scala company Lightbend, Independent Director at Jelastic, and Strategic Advisor for Eucalyptus, and is a board member of DIRTT Environmental Solutions.\n" +
                            "\n" +
                            "He is known for his love of proving \"the unknown\" and has noted that his favorite irrational number is √2. He has a framed picture of the first 1,000 digits of √2 in his office.",
                    "https://maniishankar.files.wordpress.com/2012/09/820_20_in-1995-james-gosling-launched-java2.png"
            },
            {
                "Alan Turing",
                    "Those who can imagine anything, can create impossible",
                    "Alan Mathison Turing  23 June 1912 – 7 June 1954) was an English mathematician, computer scientist, logician, cryptanalyst, philosopher and theoretical biologist.Turing was highly influential in the development of theoretical computer science, providing a formalisation of the concepts of algorithm and computation with the Turing machine, which can be considered a model of a general-purpose computer. Turing is widely considered to be the father of theoretical computer science and artificial intelligence.Despite these accomplishments, he was never fully recognised in his home country during his lifetime, due to his homosexuality, which was then a crime in the UK.\n" +
                            "\n" +
                            "During the Second World War, Turing worked for the Government Code and Cypher School (GC&CS) at Bletchley Park, Britain's codebreaking centre that produced Ultra intelligence. For a time he led Hut 8, the section that was responsible for German naval cryptanalysis. Here, he devised a number of techniques for speeding the breaking of German ciphers, including improvements to the pre-war Polish bombe method, an electromechanical machine that could find settings for the Enigma machine.\n" +
                            "\n" +
                            "Turing played a pivotal role in cracking intercepted coded messages that enabled the Allies to defeat the Nazis in many crucial engagements, including the Battle of the Atlantic, and in so doing helped win the war. Counterfactual history is difficult with respect to the effect Ultra intelligence had on the length of the war, but at the upper end it has been estimated that this work shortened the war in Europe by more than two years and saved over 14 million lives.\n" +
                            "\n" +
                            "After the war, Turing worked at the National Physical Laboratory, where he designed the Automatic Computing Engine, which was one of the first designs for a stored-program computer. In 1948, Turing joined Max Newman's Computing Machine Laboratory at the Victoria University of Manchester, where he helped develop the Manchester computers and became interested in mathematical biology. He wrote a paper on the chemical basis of morphogenesis and predicted oscillating chemical reactions such as the Belousov–Zhabotinsky reaction, first observed in the 1960s." +
                            "" +
                            "Early computers and the Turing test\n" +
                            "\n" +
                            "Plaque, 78 High Street, Hampton\n" +
                            "Between 1945 and 1947, Turing lived in Hampton, London, while he worked on the design of the ACE (Automatic Computing Engine) at the National Physical Laboratory (NPL). He presented a paper on 19 February 1946, which was the first detailed design of a stored-program computer. Von Neumann's incomplete First Draft of a Report on the EDVAC had predated Turing's paper, but it was much less detailed and, according to John R. Womersley, Superintendent of the NPL Mathematics Division, it \"contains a number of ideas which are Dr. Turing's own\". Although ACE was a feasible design, the secrecy surrounding the wartime work at Bletchley Park led to delays in starting the project and he became disillusioned. In late 1947 he returned to Cambridge for a sabbatical year during which he produced a seminal work on Intelligent Machinery that was not published in his lifetime. While he was at Cambridge, the Pilot ACE was being built in his absence. It executed its first program on 10 May 1950, and a number of later computers around the world owe much to it, including the English Electric DEUCE and the American Bendix G-15. The full version of Turing's ACE was not built until after his death.\n" +
                            "\n" +
                            "According to the memoirs of the German computer pioneer Heinz Billing from the Max Planck Institute for Physics, published by Genscher, Düsseldorf, there was a meeting between Turing and Konrad Zuse. It took place in Göttingen in 1947. The interrogation had the form of a colloquium. Participants were Womersley, Turing, Porter from England and a few German researchers like Zuse, Walther, and Billing (for more details see Herbert Bruderer, Konrad Zuse und die Schweiz).\n" +
                            "\n" +
                            "In 1948, Turing was appointed reader in the Mathematics Department at the Victoria University of Manchester. A year later, he became Deputy Director of the Computing Machine Laboratory, where he worked on software for one of the earliest stored-program computers—the Manchester Mark 1. Turing wrote the first version of the Programmer's Manual for this machine, and was recruited by Ferranti as a consultant in the development of their commercialised machine, the Ferranti Mark 1. He continued to be paid consultancy fees by Ferranti until his death. During this time, he continued to do more abstract work in mathematics, and in \"Computing Machinery and Intelligence\" (Mind, October 1950), Turing addressed the problem of artificial intelligence, and proposed an experiment that became known as the Turing test, an attempt to define a standard for a machine to be called \"intelligent\". The idea was that a computer could be said to \"think\" if a human interrogator could not tell it apart, through conversation, from a human being. In the paper, Turing suggested that rather than building a program to simulate the adult mind, it would be better rather to produce a simpler one to simulate a child's mind and then to subject it to a course of education. A reversed form of the Turing test is widely used on the Internet; the CAPTCHA test is intended to determine whether the user is a human or a computer.\n" +
                            "\n" +
                            "In 1948 Turing, working with his former undergraduate colleague, D.G. Champernowne, began writing a chess program for a computer that did not yet exist. By 1950, the program was completed and dubbed the Turbochamp. In 1952, he tried to implement it on a Ferranti Mark 1, but lacking enough power, the computer was unable to execute the program. Instead, Turing \"ran\" the program by flipping through the pages of the algorithm and carrying out its instructions on a chessboard, taking about half an hour per move. The game was recorded. According to Garry Kasparov, Turing's program \"played a recognizable game of chess.\" The program lost to Turing's colleague Alick Glennie, although it is said that it won a game against Champernowne's wife, Isabel.\n" +
                            "\n" +
                            "His Turing test was a significant, characteristically provocative, and lasting contribution to the debate regarding artificial intelligence, which continues after more than half a century.",
                "https://www.thoughtco.com/thmb/YJrEa97afMREamU_dj85OLkBFoA=/768x0/filters:no_upscale():max_bytes(150000):strip_icc()/alanturing-5b85aa874cedfd0025bf4240.png"
            }
//            },
//
//
//            {"Bill Gates","Richest Man","https://buzznigeria.com/wp-content/uploads/2015/06/bill-gates-1024x7471-640x409.jpg"},
//            {"Mark Zuckerberg","Facebook","https://www.eyerys.com/sites/default/files/mark_zuckerberg.jpg"},
//            {"Elon Musk","PayPal, Tesla, SpaceX","https://boygeniusreport.files.wordpress.com/2017/07/1500295159151.jpg?quality=98&strip=all&w=782"},
//            {"Lary Page, Sergey Brin","Google","https://image.slidesharecdn.com/sergeybrinilarrypage-131030163114-phpapp02/95/sergey-brin-i-larry-page-1-638.jpg?cb=1383150746"},
//            {"Jeff Bezos","Amazon","https://i2.cdn.turner.com/money/dam/assets/180419111403-amazon-jeff-bezos-780x439.jpg"},
//            {"Tony Stark","Stark Industries","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCc52p2yBi8Sq-hdNiyXRquOh8UGheNzgcIMPspRnpscEJ2pm1VQ"},
//            {"Steve Jobs","Apple","https://www.factsninja.com/wp-content/uploads/2017/12/Steve-Jobs-action-figure-portrait.jpg"}

    };

    public static ArrayList<Dream> getListData() {
        Dream dream  = null;
        ArrayList<Dream> list = new ArrayList<>();

        for(int i = 0;i<data.length;i++){
            dream = new Dream();
            dream.setName(data[i][0]);
            dream.setRemarks(data[i][1]);
            dream.setPhoto(data[i][3]);
            dream.setBiodata(data[i][2]);


            list.add(dream);

        }
        return list;
    };
}
